version: 2.1 # CircleCI version
orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0
jobs:
  build:
    machine: #Linux machine instead of docker environment
      image: ubuntu-2004:2024.05.1
      resource_class: large
    working_directory: ~/survey-project-creation-service # Default working directory
    steps:
      - checkout:
          path: ~/survey-project-creation-service/
      - restore_cache:
          key: survey-project-creation-service-dependency-cache-{{ checksum "src/package.json" }}
      - run:
          name: Install dependencies
          command: cd src/ && npm install
      - save_cache:
          key: survey-project-creation-service-dependency-cache-{{checksum "src/package.json"}}
          paths:
            - ./src/node_modules
      - store_artifacts:
          path: src/coverage/
          destination: /coverage/
      - run:
          name: Checking prerequisites
          command: |
            docker-compose --version
            sudo apt-get install netcat
      - run:
          name: Cloning user service
          command: cd ../ && git clone https://github.com/ELEVATE-Project/user.git --branch develop --single-branch
      - restore_cache:
          key: user-dependency-cache-{{ checksum "../user/src/package.json" }}
      - run:
          name: Install User service dependencies
          command: cd ../user/src/ && npm install
      - save_cache:
          key: user-dependency-cache-{{checksum "../user/src/package.json"}}
          paths:
            - ../user/src/node_modules
      - run:
          name: Replace SCP Service environment variables
          command: |
            # Define the file path
            ENV_FILE=~/survey-project-creation-service/dev-ops/integration_test.self_creation_portal.env

            # Replace the existing variables or append them if they don't exist
            grep -q "^CLOUD_STORAGE_PROVIDER=" $ENV_FILE && sed -i "s|^CLOUD_STORAGE_PROVIDER=.*|CLOUD_STORAGE_PROVIDER=$CLOUD_STORAGE_PROVIDER|" $ENV_FILE || echo "CLOUD_STORAGE_PROVIDER=$CLOUD_STORAGE_PROVIDER" >> $ENV_FILE
            grep -q "^CLOUD_STORAGE_ACCOUNTNAME=" $ENV_FILE && sed -i "s|^CLOUD_STORAGE_ACCOUNTNAME=.*|CLOUD_STORAGE_ACCOUNTNAME=$CLOUD_STORAGE_ACCOUNTNAME|" $ENV_FILE || echo "CLOUD_STORAGE_ACCOUNTNAME=$CLOUD_STORAGE_ACCOUNTNAME" >> $ENV_FILE
            grep -q "^CLOUD_STORAGE_SECRET=" $ENV_FILE && sed -i "s|^CLOUD_STORAGE_SECRET=.*|CLOUD_STORAGE_SECRET=$CLOUD_STORAGE_SECRET|" $ENV_FILE || echo "CLOUD_STORAGE_SECRET=$CLOUD_STORAGE_SECRET" >> $ENV_FILE
            grep -q "^CLOUD_STORAGE_BUCKETNAME=" $ENV_FILE && sed -i "s|^CLOUD_STORAGE_BUCKETNAME=.*|CLOUD_STORAGE_BUCKETNAME=$CLOUD_STORAGE_BUCKETNAME|" $ENV_FILE || echo "CLOUD_STORAGE_BUCKETNAME=$CLOUD_STORAGE_BUCKETNAME" >> $ENV_FILE
            grep -q "^CLOUD_STORAGE_REGION=" $ENV_FILE && sed -i "s|^CLOUD_STORAGE_REGION=.*|CLOUD_STORAGE_REGION=$CLOUD_STORAGE_REGION|" $ENV_FILE || echo "CLOUD_STORAGE_REGION=$CLOUD_STORAGE_REGION" >> $ENV_FILE
            grep -q "^CLOUD_STORAGE_PROJECT=" $ENV_FILE && sed -i "s|^CLOUD_STORAGE_PROJECT=.*|CLOUD_STORAGE_PROJECT=$CLOUD_STORAGE_PROJECT|" $ENV_FILE || echo "CLOUD_STORAGE_PROJECT=$CLOUD_STORAGE_PROJECT" >> $ENV_FILE
            grep -q "^CLOUD_ENDPOINT=" $ENV_FILE && sed -i "s|^CLOUD_ENDPOINT=.*|CLOUD_ENDPOINT=$CLOUD_ENDPOINT|" $ENV_FILE || echo "CLOUD_ENDPOINT=$CLOUD_ENDPOINT" >> $ENV_FILE

            # List the file to ensure changes were made
            ls -l $ENV_FILE

            # Output the file content for verification
            cat $ENV_FILE

      - run:
          name: Replace User Service environment variables
          command: |
            # Define the file path
            USER_ENV_FILE=~/survey-project-creation-service/dev-ops/integration_test.user.env

            # Replace the existing variables or append them if they don't exist
            grep -q "^CLOUD_STORAGE_PROVIDER=" $USER_ENV_FILE && sed -i "s|^CLOUD_STORAGE_PROVIDER=.*|CLOUD_STORAGE_PROVIDER=$CLOUD_STORAGE_PROVIDER|" $USER_ENV_FILE || echo "CLOUD_STORAGE_PROVIDER=$CLOUD_STORAGE_PROVIDER" >> $USER_ENV_FILE
            grep -q "^CLOUD_STORAGE_ACCOUNTNAME=" $USER_ENV_FILE && sed -i "s|^CLOUD_STORAGE_ACCOUNTNAME=.*|CLOUD_STORAGE_ACCOUNTNAME=$CLOUD_STORAGE_ACCOUNTNAME|" $USER_ENV_FILE || echo "CLOUD_STORAGE_ACCOUNTNAME=$CLOUD_STORAGE_ACCOUNTNAME" >> $USER_ENV_FILE
            grep -q "^CLOUD_STORAGE_SECRET=" $USER_ENV_FILE && sed -i "s|^CLOUD_STORAGE_SECRET=.*|CLOUD_STORAGE_SECRET=$CLOUD_STORAGE_SECRET|" $USER_ENV_FILE || echo "CLOUD_STORAGE_SECRET=$CLOUD_STORAGE_SECRET" >> $USER_ENV_FILE
            grep -q "^CLOUD_STORAGE_BUCKETNAME=" $USER_ENV_FILE && sed -i "s|^CLOUD_STORAGE_BUCKETNAME=.*|CLOUD_STORAGE_BUCKETNAME=$CLOUD_STORAGE_BUCKETNAME|" $USER_ENV_FILE || echo "CLOUD_STORAGE_BUCKETNAME=$CLOUD_STORAGE_BUCKETNAME" >> $USER_ENV_FILE
            grep -q "^CLOUD_STORAGE_REGION=" $USER_ENV_FILE && sed -i "s|^CLOUD_STORAGE_REGION=.*|CLOUD_STORAGE_REGION=$CLOUD_STORAGE_REGION|" $USER_ENV_FILE || echo "CLOUD_STORAGE_REGION=$CLOUD_STORAGE_REGION" >> $USER_ENV_FILE
            grep -q "^CLOUD_STORAGE_PROJECT=" $USER_ENV_FILE && sed -i "s|^CLOUD_STORAGE_PROJECT=.*|CLOUD_STORAGE_PROJECT=$CLOUD_STORAGE_PROJECT|" $USER_ENV_FILE || echo "CLOUD_STORAGE_PROJECT=$CLOUD_STORAGE_PROJECT" >> $USER_ENV_FILE
            grep -q "^CLOUD_ENDPOINT=" $USER_ENV_FILE && sed -i "s|^CLOUD_ENDPOINT=.*|CLOUD_ENDPOINT=$CLOUD_ENDPOINT|" $USER_ENV_FILE || echo "CLOUD_ENDPOINT=$CLOUD_ENDPOINT" >> $USER_ENV_FILE

            # List the file to ensure changes were made
            ls -l $USER_ENV_FILE

            # Output the file content for verification
            cat $USER_ENV_FILE

      - run:
          name: Starting the docker containers
          command: |-
            cd dev-ops/ && docker-compose -f testing-docker-compose.yml up --build -d
      - run:
          name: Wait for all services to be ready
          command: |
            echo "Waiting for PostgreSQL, User service, and SCP service to be ready..."
            for i in {1..60}; do
              nc -zv localhost 5432 && echo "PostgreSQL is ready" && break
              echo "Waiting for PostgreSQL... attempt $i"
              sleep 1
            done
            for i in {1..60}; do
              nc -zv localhost 5001 && echo "User service is ready" && break
              echo "Waiting for User service... attempt $i"
              sleep 1
            done
            for i in {1..60}; do
              nc -zv localhost 6001 && echo "SCP service is ready" && break
              echo "Waiting for SCP service... attempt $i"
              sleep 1
            done
      - run:
          name: Wait for Database Creation and Run Migrations
          command: |
            echo "Checking if database 'integration_test_scp' exists..."

            # Polling to check if the database is ready
            for i in {1..60}; do
              if docker exec postgres psql -U postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'integration_test_scp'" | grep -q 1; then
                echo "Database 'integration_test_scp' is ready."
                break
              fi
              echo "Database 'integration_test_scp' not ready yet... waiting (attempt $i)"
              sleep 2
            done
      - run:
          name: Create test results directory
          command: mkdir -p ./dev-ops/report
      - run:
          name: Running test cases
          command: |
            cd src/ && npm run test:integration
          #   cd src/ && npm run test:integration || true
          # continue-on-error: true
      # - run:
      #     name: Get SCP container ID and print logs
      #     command: |
      #       echo "Getting SCP container ID..."
      #       SCP_CONTAINER_ID=$(docker ps -q --filter "name=scp")
      #       echo "SCP container ID: $SCP_CONTAINER_ID"

      #       # Check if the SCP container is running
      #       if [ -z "$SCP_CONTAINER_ID" ]; then
      #         echo "SCP container is not running. Cannot fetch logs."
      #         exit 1  # Exit with an error if SCP container is not running
      #       fi

      #       # Print logs of the SCP container
      #       echo "Printing SCP container logs..."
      #       docker logs $SCP_CONTAINER_ID --tail=10000

      - store_test_results:
          path: ./dev-ops/report
      - run:
          name: Stop the docker containers - Unmap volumes
          command: |-
            cd dev-ops/ && docker-compose -f testing-docker-compose.yml down
workflows:
  build-and-test: # This is the name of the workflow,
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build:
          context:
            - SonarCloud
          filters:
            tags:
              only: \b(dev|develop|main)\b
