version: 2.1 # CircleCI version
orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0
jobs:
  build:
    machine: #Linux machine instead of docker environment
      image: ubuntu-2004:202111-01
      docker_layer_caching: true
    working_directory: ~/survey-project-creation-service # Default working directory
    steps:
      - checkout:
          path: ~/survey-project-creation-service/
      - restore_cache:
          key: survey-project-creation-service-dependency-cache-{{ checksum "src/package.json" }}
      - run:
          name: Install dependencies
          command: cd src/ && npm install #cd ../src/ && pwd &&
      - save_cache:
          key: survey-project-creation-service-dependency-cache-{{checksum "src/package.json"}}
          paths:
            - ./src/node_modules
      - store_artifacts:
          path: src/coverage/
          destination: /coverage/
      - run:
          name: Checking prerequisites
          command: |-
            docker-compose --version
      - run:
          name: Cloning user service
          command: cd ../ && git clone https://github.com/ELEVATE-Project/user.git --branch integrationFixForSCP --single-branch
      - restore_cache:
          key: user-dependency-cache-{{ checksum "../user/src/package.json" }}
      - run:
          name: Install User service dependencies
          command: cd ../user/src/ && npm install #cd ../src/ && pwd &&
      - save_cache:
          key: user-dependency-cache-{{checksum "../user/src/package.json"}}
          paths:
            - ../user/src/node_modules
      - run:
          name: Starting the docker containers
          command: |-
            cd dev-ops/ && docker-compose -f testing-docker-compose.yml up --build -d
      - run:
          name: Wait for survey-project-creation-service to be ready
          command: |-
            timeout 300 bash -c 'until docker-compose -f dev-ops/testing-docker-compose.yml ps | grep "survey-project-creation-service" | grep "healthy"; do sleep 5; done'
      
      - run: 
          name: Check docker logs
          command: |-
            docker ps && docker-compose logs --tail=1000
      - run:
          name: Create test results directory
          command: mkdir -p ./dev-ops/report
      - run:
          name: Running test cases
          command: |
            cd src/ && npm run test:integration
      - store_test_results:
          path: ./dev-ops/report
workflows:
  build-and-test: # This is the name of the workflow,
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build:
          context:
            - SonarCloud
          filters:
            tags:
              only: \b(dev|develop|main)\b
