/**
 * name : constants/common.js
 * author : Adithya Dinesh
 * Date : 29 - April - 2024
 * Description : All commonly used constants through out the service
 */

function getPaginationOffset(page, limit) {
	return (page - 1) * limit
}

function getResourceActions(resource) {
	return {
		RESOURCE_CREATED: `CREATE_${resource}`,
		RESOURCE_DELETED: `DELETE_${resource}`,
		RESOURCE_SUBMITTED: `${resource}_SUBMITTED`,
		REVIEW_STARTED: `${resource}_REVIEW_STARTED`,
		REVIEW_CHANGES_REQUESTED: `${resource}_REVIEW_CHANGES_REQUESTED`,
		REVIEW_APPROVED: `${resource}_APPROVED`,
		RESOURCE_PUBLISHED: `${resource}_PUBLISHED`,
		RESOURCE_REPORTED: `${resource}_REJECTED_AND_REPORTED`,
		RESOURCE_REJECTED: `${resource}_REJECTED`,
		REVIEW_INPROGRESS: `${resource}_REVIEW_INPROGRESS`,
		ROLLOUT_CREATED: `CREATE_${resource}`,
		ROLLOUT_DELETED: `DELETE_${resource}`,
		ROLLOUT_PUBLISHED: `${resource}_PUBLISHED`,
	}
}

module.exports = {
	pagination: {
		DEFAULT_PAGE_NO: 1,
		DEFAULT_PAGE_SIZE: 100,
	},
	getPaginationOffset,
	AUTH_METHOD: {
		NATIVE: 'native',
		USER_SERVICE: 'user_service_authenticated',
		KEYCLOAK_PUBLIC_KEY: 'keycloak_public_key',
	},
	SESSION_VERIFICATION_METHOD: {
		USER_SERVICE: 'user_service_authenticated',
	},
	internalAccessUrls: [process.env.APPLICATION_BASE_URL + 'v1/resource/publishCallback'],
	SCP_SERVICE: 'scp',
	WRITE_ACCESS: 'w',
	READ_ACCESS: 'r',
	REVIEW_TYPE_SEQUENTIAL: 'SEQUENTIAL',
	REVIEW_TYPE_PARALLEL: 'PARALLEL',
	INSTANCE_LEVEL_CONFIG_ATTRIBUTES: [
		'review_required',
		'show_reviewer_list',
		'min_approval',
		'resource_type',
		'review_type',
		'review_required_after_publish',
		'enable_entity_tagging',
		'enable_task_start_end_dates',
	],
	MIN_APPROVAL: 1,
	CONTENT_CREATOR: 'content_creator',
	REVIEWER: 'reviewer',
	RESOURCE_CREATOR: 'resource_creator',
	ADMIN_ROLE: 'admin',
	TENANT_ADMIN_ROLE: 'tenant_admin',
	ORG_ADMIN_ROLE: 'org_admin',
	CERTIFICATE_PATH: 'certificate/',
	LOGO_PATH: 'certificate_logo/',
	SIGNATURE_PATH: 'certfile_signature/',
	BASE_TEMPLATE_PATH: 'certfile_BASE_TEMPLATE/',
	CERTIFICATE_TEMPLATE_PATH: 'certfile_TEMPLATE/',
	RESOURCE_PATH: 'resource/',
	BASE_TEMPLATE: 'BASE_TEMPLATE',
	CERTIFICATE_TEMPLATE: 'CERTIFICATE_TEMPLATE',
	SIGNATURE: 'signature',
	LOGO: 'logo',
	CERTIFICATE: 'certificate',
	CLOUD_SERVICE_LINK_EXPIRY_TIME: process.env.DOWNLOAD_URL_EXPIRATION_DURATION || 1200,
	CLOUD_SERVICE: ['azure', 'gcloud'],
	STATUS_ACTIVE: 'ACTIVE',
	CREATED_BY_SYSTEM: '0',
	PROJECT: 'project',
	RESOURCES: 'resources',
	FILTER_ALL: 'ALL',
	SORT_DESC: 'DESC',
	SORT_ASC: 'ASC',
	CREATED_AT: 'created_at',
	UPDATED_AT: 'updated_at',
	FILTER: 'filter',
	TYPE: 'type',
	STATUS: 'status',
	SEARCH: 'search',
	SORT_BY: 'sort_by',
	SORT_ORDER: 'sort_order',
	URL: 'url',
	FILE_PATH: 'filePath',
	LISTING: 'listing',
	PAGE_STATUS_VALUES: {
		drafts: ['DRAFT'],
		submitted_for_review: [
			'INPROGRESS',
			'SUBMITTED',
			'PUBLISHED',
			'REJECTED',
			'REJECTED_AND_REPORTED',
			'REQUESTED_FOR_CHANGES',
		],
	},
	REVIEW_STATUS_UP_FOR_REVIEW: ['INPROGRESS', 'NOT_STARTED', 'CHANGES_UPDATED', 'STARTED'],
	PAGE_STATUS_DRAFTS: 'drafts',
	PAGE_STATUS_SUBMITTED_FOR_REVIEW: 'submitted_for_review',
	RESOURCE_STATUS_DRAFT: 'DRAFT',
	RESOURCE_STATUS_PUBLISHED: 'PUBLISHED',
	RESOURCE_STATUS_STARTED: 'STARTED',
	RESOURCE_STATUS_REJECTED: 'REJECTED',
	RESOURCE_STATUS_IN_REVIEW: 'IN_REVIEW',
	RESOURCE_STATUS_SUBMITTED: 'SUBMITTED',
	RESOURCE_STATUS_REJECTED_AND_REPORTED: 'REJECTED_AND_REPORTED',
	STATUS_RESOLVED: 'RESOLVED',
	ALL_USER_ROLES: 'all',
	LIMIT: 100,
	CONTENT: 'content',
	REVIEW_STATUS_NOT_STARTED: 'NOT_STARTED',
	REVIEW_STATUS_STARTED: 'STARTED',
	REVIEW_STATUS_INPROGRESS: 'INPROGRESS',
	REVIEW_STATUS_REQUESTED_FOR_CHANGES: 'REQUESTED_FOR_CHANGES',
	REVIEW_STATUS_REJECTED: 'REJECTED',
	REVIEW_STATUS_REJECTED_AND_REPORTED: 'REJECTED_AND_REPORTED',
	REVIEW_STATUS_APPROVED: 'APPROVED',
	REVIEW_STATUS_CHANGES_UPDATED: 'CHANGES_UPDATED',
	TRUE: true,
	FALSE: false,
	TASKS: 'tasks',
	TASK: 'task',
	COMMENT: 'comment',
	SUBTASKS: 'subTasks',
	ROLLOUT: 'rollouts',
	OBJECT: 'object',
	roleValidationPaths: [
		'/scp/v1/resource/list',
		'/scp/v1/projects/reviewerList',
		'/scp/v1/projects/update',
		'/scp/v1/projects/details/',
		'/scp/v1/certificate/list',
		'/scp/v1/resource/list',
		'/scp/v1/certificate/list',
		'/scp/v1/certificate/update',
		'/scp/v1/comment/update',
		'/scp/v1/comment/list',
	],
	PUBLIC_ROLE: 'public',
	RESOURCE_TITLE: 'title',
	ROLLOUT_TITLE: 'title',
	BODY: 'body',
	TASK_EVIDENCE: 'evidence_details',
	REQUEST_METHOD_DELETE: 'DELETE',
	FILE_TYPE: 'file_types',
	CHILDREN: 'children',
	SELF: 'self',
	RESOURCE_TYPE_PROGRAM: 'program',
	COMMENT_STATUS_DRAFT: 'DRAFT',
	REVIEW_COLUMN_REJECTED_AT: 'rejected_at',
	REVIEW_STATUS: 'review_status',
	COMMENT_STATUS_OPEN: 'OPEN',
	LEARNING_RESOURCE: 'learning_resources',
	LEARNING_RESOURCE_NAME: 'learning_resource_name',
	SOLUTION_DETAILS: 'solution_details',
	TASK_ALLOWED_FILE_TYPES: 'file_types',
	ALLOWED_FILE_TYPES: {
		images: ['jpg', 'png', 'jpeg', 'bmp', 'gif', 'tiff', 'heif'],
		document: ['pdf'],
		videos: ['mp4', '3gp', 'm4v', 'mov', 'mkv', 'mpeg', 'ogg', 'webm', '3gpp', 'wmv', 'avi', 'flv'],
		audio: ['mp3', 'mp4', 'acc', 'flac', 'wav', 'midi', 'aiff'],
	},
	MAX_CHARACTER_LIMIT: 'max_char_limit',
	DATA_TYPE_NUMBER: 'number',
	SUB_TASK: 'subtask',
	MIN_NO_OF_EVIDENCES: 'min_no_of_evidences',
	NAME: 'name',
	DATA_TYPE_BOOLEAN: 'boolean',
	KAFKA_ON: 'ON',
	ENTITY_TYPE_MODELS: {
		project: ['project', 'tasks', 'subTasks'],
		program: ['program'],
		targeting: ['targeting'],
	},
	MODEL_NAMES: {
		RESOURCE: 'Resource',
		ROLLOUT: 'Rollouts',
		TARGETING: 'targeting',
	},
	USER_ACTIONS: {
		project: getResourceActions('PROJECT'),
		rollout_program: getResourceActions('PROGRAM_ROLLOUT'),
		rollout_solution: getResourceActions('SOLUTION_ROLLOUT'),
		program: getResourceActions('PROGRAM'),
	},
	EVENT_ADD_USER_ACTION: 'addUserAction',
	REQUEST_TIMEOUT_MS: 3000,
	CURRENT_USER: 'You',
	ACTIVITY_DATE_TIME_OPTIONS: {
		day: 'numeric',
		month: 'long',
		year: 'numeric',
		hour: 'numeric',
		minute: 'numeric',
		second: 'numeric',
		hour12: true, // Use 12-hour clock with AM/PM
	},
	REQUIRED_VALIDATION: 'required',
	REGEX_VALIDATION: 'regex',
	END_DATE_VALIDATION: 'end_date_check',
	START_DATE: 'start_date',
	END_DATE: 'end_date',
	MAX_LENGTH_VALIDATION: 'max_length',
	RESOURCE_STAGE_CREATION: 'CREATION',
	RESOURCE_STAGE_REVIEW: 'REVIEW',
	RESOURCE_STAGE_COMPLETION: 'COMPLETION',
	LINK: 'link',
	DURATION: 'duration',
	RECOMMENDED_DURATION: 'recommended_duration',
	NUMBER: 'number',
	STRING: 'string',
	ROLLOUT_STATUS_PUBLISHED: 'ROLLED_OUT',
	ROLLOUT_STATUS_PENDING: 'DRAFT',
	ROLLOUT_STATUS_ROLLED_OUT: 'ROLLED_OUT',
	ROLLOUT_STATUS_INACTIVE: 'INACTIVE',
	ROLLOUT_STATUS_PROCESSING: 'PROCESSING',
	ROLLOUT_STATUS_FAILED: 'FAILED',
	ROLL_OUT: 'rollout',
	ROLL_OUT_MODEL: 'rollouts',
	ROLLOUT_TYPE_PROGRAM: 'program',
	ROLLOUT_TYPE_SOLUTION: 'solution',
	ROLL_OUT_PATH: 'rollout/',
	PROJECT_UPLOAD_FILE_NAME: 'project.json',
	ROLLOUT_UPLOAD_FILE_NAME: 'rollout.json',
	PROGRAM_UPLOAD_FILE_NAME: 'program.json',
	SUFFIX_CHILD: '_CHILD',
	SOLUTIONS_RESOURCE_TYPE: {
		project: 'Improvement Project Solution',
	},
	SOLUTIONS_TYPE: {
		project: 'improvementProject',
	},
	PUBLISHED_STATUS: 'published',
	CONSUMPTION_SERVICE_SELF: 'self',
	SUNBIRD: 'sunbird',
	ELEVATE: 'elevate',
	INTERNAL_ACCESS_TOKEN: 'internal-access-token',
	UPLOAD_FILE_NAME: {
		project: 'project.json',
		program: 'program.json',
	},
	ORGANIZATION_KEY: 'organization_code',
	PROJECTION_KEY_ASTERISK: '*',
	MONGO_DB_MODE_INDIVIDUAL: 'individual',
	MONGO_DB_MODE_SHARED: 'shared',
	TARGETING: 'targeting_criteria',
	OBSERVATION: 'observation',
	OBSERVATION_WITH_RUBRICS: 'observation_with_rubrics',
	SURVEY: 'survey',
	ORG_POLICY_CURRENT: 'CURRENT',
	SCOPE_ELEMENT_ORGANIZATIONS: 'organizations',
	TARGETING_ALL: 'ALL',
	TASK_TYPE_REFLECTION: 'reflection',
	START_REFLECTION: 'Start Reflection',
	ENTITY_TYPE: 'entity_type',
	OPERATION_APPEND: 'append',
	OPERATION_REMOVE: 'remove',
	PUT: 'PUT',
	ALL: 'ALL',
	IS_EXTERNAL: 'is_external',
	DEPENDED_ON: 'depended_on',
	CREATE: 'CREATE',
	UPDATE: 'UPDATE',
	VALID_POLICIES: {
		ALL: 'ALL',
		ASSOCIATED: 'ASSOCIATED',
		CURRENT: 'CURRENT',
	},
	TASK_TYPE_PROJECT: 'improvement_projects',
	PROJECT_ID: 'project_id',
	CLOUD_BUCKET_TYPE_PRIVATE: 'private',
}
