
SELECT create_distributed_table('certificate_base_templates', 'organization_code');
SELECT create_distributed_table('comments', 'resource_id');
SELECT create_distributed_table('entities', 'entity_type_id');
SELECT create_distributed_table('entity_types', 'organization_code');
SELECT create_distributed_table('forms', 'organization_code');
SELECT create_distributed_table('organization_extensions', 'organization_code');
SELECT create_distributed_table('resources', 'organization_code');
SELECT create_distributed_table('resource_creator_mapping', 'creator_id');
SELECT create_distributed_table('review_resources', 'reviewer_id');
SELECT create_distributed_table('review_stages', 'organization_code');
SELECT create_distributed_table('reviews', 'organization_code');
SELECT create_distributed_table('activities', 'object_id');
SELECT create_distributed_table('organization_configs', 'organization_code');


SELECT create_distributed_table('rollouts', 'organization_code');
SELECT create_distributed_table('program_resource_mapping', 'organization_code');